dependencies:
  image: node:9
  command:
    - "yarn"

tasks:
  - name: app
    image: node:9
    command: "yarn start"
  - name: unit_tests
    image: markadams/chromium-xvfb-js
    command: "npm run test"
