beforeTasks:
  image: node:9
  command:
    - "yarn --version"

tasks:
  - name: app
    image: node:9
    command: "echo node --version && sleep 10m"
  - name: random
    image: node:9
    command: "echo npm --version && sleep 10m"
